/* ============================================================
   Website ke UI words — teen bhashaon me
   (poori website ka text yahan se badlega)
   ============================================================ */

window.KG = window.KG || {};

KG.UI = {
  hi: {
    /* header */
    brand: "कविता का घर",
    sub: ["કવિતાનું ઘર", "Kavita Ka Ghar"],
    langBtn: "🌐 भाषा",
    /* hero */
    heroTitle: "Play Group से Class 1 तक",
    heroSub: "हर कविता 3 भाषाओं में — हिन्दी, गुजराती, English। खुद सुनाओ, खुद रिकॉर्ड करो।",
    voiceBtn: "🎤 अपनी आवाज़",
    voiceTip: "🎤 अपनी आवाज़: कोई कविता खोलो, फिर 'मेरे घर से बोलो' दबाओ — आपकी रिकॉर्डिंग बची रहेगी।",
    /* class */
    pickClass: "📚 कक्षा चुनें",
    classTip: "जो चाहिए वही बैठक चुन लो।",
    allClasses: "सभी कक्षाएँ",
    homeBtn: "🏠 होम",
    homeNote1: "ऊपर वाला हरा बटन दबाओ",
    homeNote2: "ઉપરના લીલા બટને દબાવો",
    homeNote3: "Tap the green button above",
    homeNoteText: "वहाँ से अपनी कक्षा चुनो — फिर सिर्फ उसी की कविताएँ दिखेंगी।",
    /* list */
    sabhi: "🌈 सभी कविताएँ",
    tradi: "🏛 पारंपरिक",
    kavitayen: "कविताएँ",
    open: "Padhein",
    play: "Play",
    readIt: "पढ़ें",
    /* reader */
    tabs: "भाषा बदलें",
    allThree: "📖 तीनों एक साथ",
    allThreeTag: "📖 तीनों भाषाएँ",
    playBtn: "Play / Suno",
    playing: "चल रही है…",
    stopBtn: "⏹ रुको",
    compVoice: "🖥️ Computer की आवाज़",
    speed: "Speed:",
    slow: "Dheere", mid: "Theek", fast: "Tez",
    recBtn: "🎤 मेरे घर से बोलो",
    recStop: "⏹ बंद करो",
    playRec: "▶️ मेरी रिकॉर्डिंग सुनाओ",
    dlRec: "⬇️ रिकॉर्डिंग सेव करो",
    pdf: "🖨 PDF / Print",
    img: "🖼 तस्वीर सेव करो",
    videoLbl: "🎥 अपना वीडियो (optional):",
    hint: "💡 रिकॉर्डिंग सिर्फ आपके फ़ोन में save होती है — कहीं upload नहीं। वीडियो के लिए सिर्फ अपना link डालें।",
    prev: "← पिछली कविता",
    next: "अगली कविता →",
    audioOk: "🎧 इस कविता की audio तैयार है — हिन्दी ✅ · ગુજરાતી ✅ · English ✅",
    dlAudio: "⬇️ Audio save करो",
    teacherRec: "आपकी recording",
    recPlaying: "यही चलेगी",
    guide: "▸ सिर्फ computer की आवाज़ से sunana hai?",
    guideNote: "हर कविता की MP3 audio website पर bani hui hai — ▶ Play usi ko chalata hai, isliye awaaz hamesha aayegi.",
    close: "बंद करें",
    /* language popup */
    chooseLang: "भाषा चुनें",
    langTip: "पूरी website इसी भाषा में दिखेगी",
    notSupported: "😢 यह browser speech support नहीं करता।",
    noVoice: "⚠️ अभी आवाज़ नहीं मिली। ऊपर वाला ↻ दबाओ।"
  },

  gu: {
    brand: "કવિતાનું ઘર",
    sub: ["कविता का घर", "Kavita Ka Ghar"],
    langBtn: "🌐 ભાષા",
    heroTitle: "Play Group થી Class 1 સુધી",
    heroSub: "દરેક કવિતા 3 ભાષાઓમાં — હિન્દી, ગુજરાતી, English. તમારી જાતે સુનાવો, રેકોર્ડ કરો.",
    voiceBtn: "🎤 તમારી અવાજ",
    voiceTip: "🎤 તમારી અવાજ: કોઈ કવિતા ખોલો, પછી 'મારા ઘરથી બોલો' દબાવો — તમારી રેકોર્ડિંગ સચવાશે.",
    pickClass: "📚 વર્ગ પસંદ કરો",
    classTip: "જોઈએ ત્યાં બેઠક પસંદ કરો.",
    allClasses: "બધા વર્ગો",
    homeBtn: "🏠 હોમ",
    homeNote1: "ઊપરના લીલા બટને દબાવો",
    homeNote2: "ऊपर वाला हरा बटन दबाओ",
    homeNote3: "Tap the green button above",
    homeNoteText: "ત્યાંથી પોતાનો વર્ગ પસંદ કરો — પછી ફક્ત એ જ કવિતાઓ દેખાશે.",
    sabhi: "🌈 બધી કવિતાઓ",
    tradi: "🏛 પારંપરિક",
    kavitayen: "કવિતાઓ",
    open: "વાંચો",
    play: "Play",
    readIt: "વાંચો",
    tabs: "ભાષા બદલો",
    allThree: "📖 ત્રણેય સાથે",
    allThreeTag: "📖 ત્રણ ભાષાઓ",
    playBtn: "Play / સુનાવો",
    playing: "ચાલી રહી છે…",
    stopBtn: "⏹ બંધ કરો",
    compVoice: "🖥️ Computer ની અવાજ",
    speed: "Speed:",
    slow: "Dheere", mid: "Theek", fast: "Tez",
    recBtn: "🎤 મારા ઘરથી બોલો",
    recStop: "⏹ બંધ કરો",
    playRec: "▶️ મારી રેકોર્ડિંગ સુનાવો",
    dlRec: "⬇️ રેકોર્ડિંગ સેવ કરો",
    pdf: "🖨 PDF / Print",
    img: "🖼 તસ્વીર સેવ કરો",
    videoLbl: "🎥 તમારો વિડિયો (optional):",
    hint: "💡 રેકોર્ડિંગ ફક્ત તમારા ફોનમાં save થાય છે — ક્યાં upload થતું નથી. વિડિયો માટે ફક્ત તમારો link નાખો.",
    prev: "← પાછલી કવિતા",
    next: "આગળની કવિતા →",
    audioOk: "🎧 આ કવિતાની audio તૈયાર છે — હિન્દી ✅ · ગુજરાતી ✅ · English ✅",
    dlAudio: "⬇️ Audio save કરો",
    guide: "▸ ફક્ત computer ની અવાજથી સુનાવવું છે?",
    guideNote: "દરેક કવિતાની MP3 audio website પર બની છે — ▶ Play એ જ ચલાવે છે, એટલે અવાજ હંમેશા આવશે.",
    close: "બંધ કરો",
    chooseLang: "ભાષા પસંદ કરો",
    langTip: "આખી website આ જ ભાષામાં દેખાશે",
    notSupported: "😢 આ browser speech support કરતો નથી.",
    noVoice: "⚠️ હજી અવાજ મળી નથી. ઉપરનો ↻ દબાવો."
  },

  en: {
    brand: "Kavita Ka Ghar",
    sub: ["कविता का घर", "કવિતાનું ઘર"],
    langBtn: "🌐 Language",
    heroTitle: "From Play Group to Class 1",
    heroSub: "Every poem in 3 languages — Hindi, Gujarati, English. Listen aloud, and record your own voice.",
    voiceBtn: "🎤 Your own voice",
    voiceTip: "🎤 Your own voice: open any poem, then tap 'Record from home' — your recording will be saved.",
    pickClass: "📚 Choose Class",
    classTip: "Please choose the class you need.",
    allClasses: "All Classes",
    homeBtn: "🏠 Home",
    homeNote1: "ऊपर वाला हरा बटन दबाओ",
    homeNote2: "ઉપરના લીલા બટને દબાવો",
    homeNote3: "Tap the green button above",
    homeNoteText: "Choose your class there — then only that class's poems will show.",
    sabhi: "🌈 All Poems",
    tradi: "🏛 Traditional",
    kavitayen: "poems",
    open: "Open",
    play: "Play",
    readIt: "Read",
    tabs: "Change language",
    allThree: "📖 All three together",
    allThreeTag: "📖 Three languages",
    playBtn: "Play / Listen",
    playing: "Playing…",
    stopBtn: "⏹ Stop",
    compVoice: "🖥️ Computer voice",
    speed: "Speed:",
    slow: "Dheere", mid: "Theek", fast: "Tez",
    recBtn: "🎤 Record from home",
    recStop: "⏹ Stop recording",
    playRec: "▶️ Play my recording",
    dlRec: "⬇️ Save recording",
    pdf: "🖨 PDF / Print",
    img: "🖼 Save picture",
    videoLbl: "🎥 Your video (optional):",
    hint: "💡 Recording is saved only on your device — never uploaded. For video, use only your own link.",
    prev: "← Previous poem",
    next: "Next poem →",
    audioOk: "🎧 This poem's audio is ready — Hindi ✅ · Gujarati ✅ · English ✅",
    dlAudio: "⬇️ Save audio",
    guide: "▸ Listen using only the computer's voice?",
    guideNote: "Every poem has its own MP3 audio on this website — ▶ Play uses it, so you will always hear sound.",
    close: "Close",
    chooseLang: "Choose language",
    langTip: "The whole website will show in this language",
    notSupported: "😢 This browser does not support speech.",
    noVoice: "⚠️ No voice found yet. Tap ↻ above."
  }
};

/* chhota helper:  t("kavitayen") */
KG.t = function (lang, key) {
  const box = KG.UI[lang] || KG.UI.hi;
  return box[key] !== undefined ? box[key] : (KG.UI.hi[key] || key);
};